menu:
  博文: /
  归档: /archives/
  生活: /categories/live/
  读书: /categories/read/
  关于: /abouts/

widgets:
  - category
  - tag
  - tagcloud
  - archive

# count
show_count: true
favicon: https://bubuzou.oss-cn-shenzhen.aliyuncs.com/blog/202010/favicon.ico
logo: https://z3.ax1x.com/2021/06/27/RYrzNQ.png
style: https://bubuzou.oss-cn-shenzhen.aliyuncs.com/blog/202010/bubuzou.css
header:
  style: "background: linear-gradient(to right, #4b6cb7, #182848);box-shadow: 0px 1px 1px #182828;"
# Comment
#changyan: bubuzou
leancloud:
  appid: aD8jJBpu4oew3ovNY73z6Rdq-gzGzoHsz # 填写您的appid
  appkey: FdzS5SOPHdhYQoEUngQ8K2QW # 填写您的appkey
  comment: true # 是否开启评论系统
  timer: true # 是否开启文章统计


# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016

